# Generated by Django 5.1.2 on 2024-11-05 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('escudos', models.IntegerField(default=0)),
                ('radar', models.IntegerField(default=0)),
                ('comunicaciones', models.IntegerField(default=0)),
                ('resistencia', models.IntegerField(default=20)),
                ('capacidadTripulantes', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.CharField(default='', max_length=255)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('radar', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('poder', models.IntegerField(default=0)),
                ('asignado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones', models.IntegerField(default=100)),
                ('oro', models.IntegerField(default=100)),
                ('recursos', models.IntegerField(default=0)),
                ('poder', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tripulacion_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tripulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tripulacion')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBatalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatoBatalla', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('atacante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atacante', to='web.usuario')),
                ('defensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defensor', to='web.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Nave_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resistencia', models.IntegerField(default=0)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('escudos', models.IntegerField(default=0)),
                ('radar', models.IntegerField(default=0)),
                ('comunicaciones', models.IntegerField(default=0)),
                ('Nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nave')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
    ]
