# Generated by Django 5.1.2 on 2024-10-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripulacion',
            name='ataque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripulacion',
            name='defensa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tripulacion',
            name='imagen',
            field=models.CharField(default='', max_length=70),
        ),
    ]
