# Generated by Django 5.1.2 on 2024-11-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_registrobatalla_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobatalla',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
