# Generated by Django 5.1.2 on 2024-10-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_tripulacion_ataque_tripulacion_defensa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ataque', models.IntegerField(default=0)),
                ('defensa', models.IntegerField(default=0)),
                ('escudos', models.IntegerField(default=0)),
                ('radar', models.IntegerField(default=0)),
                ('comunicaciones', models.IntegerField(default=0)),
                ('capacidadTripulantes', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('acciones', models.IntegerField(default=100)),
                ('poder', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nave_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.nave')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
    ]
