# Generated by Django 5.1.2 on 2024-10-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripulacion',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
