# Generated by Django 5.1.2 on 2024-10-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_tripulacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripulacion',
            name='imagen',
            field=models.CharField(default='', max_length=255),
        ),
    ]
