# Generated by Django 5.1.2 on 2024-10-30 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_tripulacion_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tripulacion_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tripulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tripulacion')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
            ],
        ),
    ]
