# Generated by Django 5.1.2 on 2024-11-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_usuario_oro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripulacion',
            name='asignado',
            field=models.BooleanField(default=False),
        ),
    ]
