# Generated by Django 5.1.2 on 2024-11-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_tripulacion_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='resistencia',
            field=models.IntegerField(default=0),
        ),
    ]
