# Generated by Django 5.1.2 on 2024-11-02 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_nave_resistencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulacion_usuario',
            name='resistencia',
        ),
        migrations.AddField(
            model_name='nave_usuario',
            name='resistencia',
            field=models.IntegerField(default=0),
        ),
    ]
