# Generated by Django 5.1.2 on 2024-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_tripulacion_usuario_resistencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nave',
            name='resistencia',
            field=models.IntegerField(default=20),
        ),
    ]
