# Generated by Django 5.1.2 on 2024-11-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_nave_resistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripulacion',
            name='radar',
            field=models.IntegerField(default=0),
        ),
    ]
